namespace EZManifest.Models;

public sealed class SteamCdnRegion
{
    public int CellId { get; init; }
    public string DisplayName { get; init; } = string.Empty;

    public override string ToString() => DisplayName;
}

public static class SteamCdnRegions
{
    /// <summary>
    /// Steam content cells from CellMap.vdf (non-deprecated location cells).
    /// Cell 0 = Auto.
    /// </summary>
    public static IReadOnlyList<SteamCdnRegion> All { get; } =
    [
        new() { CellId = 0, DisplayName = "Auto (Steam default)" },
        new() { CellId = 1, DisplayName = "US - Chicago" },
        new() { CellId = 2, DisplayName = "US - New York" },
        new() { CellId = 4, DisplayName = "UK - London" },
        new() { CellId = 5, DisplayName = "Germany - Frankfurt" },
        new() { CellId = 7, DisplayName = "Russia - Moscow" },
        new() { CellId = 8, DisplayName = "South Korea - Seoul" },
        new() { CellId = 9, DisplayName = "Taiwan" },
        new() { CellId = 10, DisplayName = "US - San Jose" },
        new() { CellId = 11, DisplayName = "US - Phoenix" },
        new() { CellId = 12, DisplayName = "US - Miami" },
        new() { CellId = 14, DisplayName = "France - Paris" },
        new() { CellId = 15, DisplayName = "Netherlands" },
        new() { CellId = 16, DisplayName = "Romania" },
        new() { CellId = 20, DisplayName = "Canada - Toronto" },
        new() { CellId = 22, DisplayName = "New Zealand" },
        new() { CellId = 25, DisplayName = "Brazil - Sao Paulo" },
        new() { CellId = 26, DisplayName = "South Africa - Johannesburg" },
        new() { CellId = 29, DisplayName = "Iceland, Greenland, and Faroe Islands" },
        new() { CellId = 30, DisplayName = "Israel" },
        new() { CellId = 31, DisplayName = "US - Seattle" },
        new() { CellId = 32, DisplayName = "Japan - Tokyo" },
        new() { CellId = 33, DisplayName = "China - Hong Kong" },
        new() { CellId = 34, DisplayName = "Thailand" },
        new() { CellId = 35, DisplayName = "Singapore" },
        new() { CellId = 36, DisplayName = "India - Mumbai" },
        new() { CellId = 37, DisplayName = "Italy - Rome" },
        new() { CellId = 38, DisplayName = "Poland - Warsaw" },
        new() { CellId = 39, DisplayName = "Russia - Yekaterinburg" },
        new() { CellId = 40, DisplayName = "Spain - Madrid" },
        new() { CellId = 41, DisplayName = "Denmark" },
        new() { CellId = 42, DisplayName = "Czech Republic" },
        new() { CellId = 43, DisplayName = "Greece" },
        new() { CellId = 44, DisplayName = "Indonesia" },
        new() { CellId = 45, DisplayName = "Philippines - Manila" },
        new() { CellId = 46, DisplayName = "China - Beijing" },
        new() { CellId = 47, DisplayName = "China - Shanghai" },
        new() { CellId = 48, DisplayName = "China - Chengdu" },
        new() { CellId = 49, DisplayName = "US - Denver" },
        new() { CellId = 50, DisplayName = "US - Atlanta" },
        new() { CellId = 51, DisplayName = "Australia - QLD" },
        new() { CellId = 52, DisplayName = "Australia - NSW" },
        new() { CellId = 53, DisplayName = "Australia - VIC" },
        new() { CellId = 54, DisplayName = "Australia - SA" },
        new() { CellId = 55, DisplayName = "Australia - WA" },
        new() { CellId = 62, DisplayName = "Russia - Novosibirsk" },
        new() { CellId = 63, DisplayName = "US - Washington, DC" },
        new() { CellId = 64, DisplayName = "US - Los Angeles" },
        new() { CellId = 65, DisplayName = "US - Dallas" },
        new() { CellId = 66, DisplayName = "Sweden - Stockholm" },
        new() { CellId = 67, DisplayName = "Norway" },
        new() { CellId = 68, DisplayName = "Finland" },
        new() { CellId = 69, DisplayName = "Ireland" },
        new() { CellId = 70, DisplayName = "Cambodia" },
        new() { CellId = 71, DisplayName = "Vietnam" },
        new() { CellId = 72, DisplayName = "Malaysia" },
        new() { CellId = 73, DisplayName = "Ukraine - Kiev" },
        new() { CellId = 74, DisplayName = "US - San Diego" },
        new() { CellId = 75, DisplayName = "US - Sacramento" },
        new() { CellId = 76, DisplayName = "US - Minneapolis" },
        new() { CellId = 77, DisplayName = "US - St. Louis" },
        new() { CellId = 78, DisplayName = "US - Houston" },
        new() { CellId = 79, DisplayName = "US - Detroit" },
        new() { CellId = 80, DisplayName = "US - Pittsburgh" },
        new() { CellId = 81, DisplayName = "Canada - Montreal" },
        new() { CellId = 82, DisplayName = "US - Boston" },
        new() { CellId = 83, DisplayName = "US - Philadelphia" },
        new() { CellId = 84, DisplayName = "US - Charlotte" },
        new() { CellId = 85, DisplayName = "UK - Manchester" },
        new() { CellId = 86, DisplayName = "Belgium" },
        new() { CellId = 87, DisplayName = "Germany - Dusseldorf" },
        new() { CellId = 88, DisplayName = "Switzerland" },
        new() { CellId = 89, DisplayName = "Germany - Hamburg" },
        new() { CellId = 90, DisplayName = "Germany - Berlin" },
        new() { CellId = 91, DisplayName = "Germany - Munich" },
        new() { CellId = 92, DisplayName = "Austria" },
        new() { CellId = 93, DisplayName = "Hungary" },
        new() { CellId = 94, DisplayName = "Canada - Vancouver" },
        new() { CellId = 95, DisplayName = "US - Columbus" },
        new() { CellId = 96, DisplayName = "France - Marseille" },
        new() { CellId = 97, DisplayName = "South Africa - Cape Town" },
        new() { CellId = 102, DisplayName = "LAN Event (USA)" },
        new() { CellId = 103, DisplayName = "LAN Event (Europe)" },
        new() { CellId = 104, DisplayName = "LAN Event (Asia)" },
        new() { CellId = 115, DisplayName = "Mexico" },
        new() { CellId = 116, DisplayName = "Argentina" },
        new() { CellId = 117, DisplayName = "Chile" },
        new() { CellId = 118, DisplayName = "Peru" },
        new() { CellId = 119, DisplayName = "Colombia" },
        new() { CellId = 124, DisplayName = "Turkey - Istanbul" },
        new() { CellId = 125, DisplayName = "Egypt" },
        new() { CellId = 126, DisplayName = "Saudi Arabia" },
        new() { CellId = 127, DisplayName = "United Arab Emirates" },
        new() { CellId = 128, DisplayName = "Pakistan" },
        new() { CellId = 129, DisplayName = "Luxembourg" },
        new() { CellId = 130, DisplayName = "West Africa" },
        new() { CellId = 131, DisplayName = "East Africa" },
        new() { CellId = 132, DisplayName = "Northwest Africa" },
        new() { CellId = 133, DisplayName = "Canada - Edmonton" },
        new() { CellId = 134, DisplayName = "Canada - Calgary" },
        new() { CellId = 135, DisplayName = "Canada - Winnipeg" },
        new() { CellId = 136, DisplayName = "Canada - Ottawa" },
        new() { CellId = 137, DisplayName = "China (Perfect World Unicom)" },
        new() { CellId = 138, DisplayName = "China (Perfect World Telecom)" },
        new() { CellId = 139, DisplayName = "Central America" },
        new() { CellId = 140, DisplayName = "Caribbean" },
        new() { CellId = 141, DisplayName = "India - Chennai" },
        new() { CellId = 142, DisplayName = "India - Delhi" },
        new() { CellId = 143, DisplayName = "India - Bangalore" },
        new() { CellId = 144, DisplayName = "India - Hyderabad" },
        new() { CellId = 145, DisplayName = "India - Kolkata" },
        new() { CellId = 146, DisplayName = "US - Honolulu" },
        new() { CellId = 147, DisplayName = "US - Anchorage" },
        new() { CellId = 148, DisplayName = "China - Guangzhou" },
        new() { CellId = 149, DisplayName = "Russia - St. Petersburg" },
        new() { CellId = 150, DisplayName = "Russia - Rostov-na-Donu" },
        new() { CellId = 151, DisplayName = "Russia - Kazan" },
        new() { CellId = 152, DisplayName = "Russia - Vladivostok" },
        new() { CellId = 153, DisplayName = "Brazil - Recife" },
        new() { CellId = 154, DisplayName = "Brazil - Brasilia" },
        new() { CellId = 155, DisplayName = "Brazil - Rio de Janeiro" },
        new() { CellId = 156, DisplayName = "Brazil - Porto Alegre" },
        new() { CellId = 157, DisplayName = "Russia - Irkutsk" },
        new() { CellId = 158, DisplayName = "Kazakhstan" },
        new() { CellId = 159, DisplayName = "China - Wuhan" },
        new() { CellId = 160, DisplayName = "China - Xi'an" },
        new() { CellId = 161, DisplayName = "Mongolia" },
        new() { CellId = 162, DisplayName = "Venezuela" },
        new() { CellId = 163, DisplayName = "Ecuador" },
        new() { CellId = 164, DisplayName = "Bolivia" },
        new() { CellId = 165, DisplayName = "Belarus" },
        new() { CellId = 166, DisplayName = "China - Harbin" },
        new() { CellId = 167, DisplayName = "China - Kunming" },
        new() { CellId = 168, DisplayName = "China - Qingdao" },
        new() { CellId = 169, DisplayName = "China - Urumqi" },
        new() { CellId = 170, DisplayName = "China - Zhengzhou" },
        new() { CellId = 171, DisplayName = "China - Changsha" },
        new() { CellId = 172, DisplayName = "Caucasus" },
        new() { CellId = 173, DisplayName = "Central Asia" },
        new() { CellId = 174, DisplayName = "Pacific Islands" },
        new() { CellId = 175, DisplayName = "Sweden - Malmo" },
        new() { CellId = 176, DisplayName = "Sweden - Gothenburg" },
        new() { CellId = 177, DisplayName = "Japan - Sapporo" },
        new() { CellId = 178, DisplayName = "Japan - Sendai" },
        new() { CellId = 179, DisplayName = "Japan - Nagoya" },
        new() { CellId = 180, DisplayName = "Japan - Osaka" },
        new() { CellId = 181, DisplayName = "Japan - Fukuoka" },
        new() { CellId = 182, DisplayName = "South Korea - Busan" },
        new() { CellId = 183, DisplayName = "Poland - Katowice" },
        new() { CellId = 184, DisplayName = "Italy - Milan" },
        new() { CellId = 185, DisplayName = "Portugal" },
        new() { CellId = 186, DisplayName = "Spain - Barcelona" },
        new() { CellId = 187, DisplayName = "Spain - Valencia" },
        new() { CellId = 188, DisplayName = "Spain - Malaga" },
        new() { CellId = 189, DisplayName = "Turkey - Ankara" },
        new() { CellId = 190, DisplayName = "Turkey - Izmir" },
        new() { CellId = 191, DisplayName = "Ukraine - Odessa" },
        new() { CellId = 192, DisplayName = "Ukraine - Lviv" },
        new() { CellId = 193, DisplayName = "Ukraine - Kharkiv" },
        new() { CellId = 194, DisplayName = "Bulgaria" },
        new() { CellId = 195, DisplayName = "Croatia" },
        new() { CellId = 196, DisplayName = "Lithuania" },
        new() { CellId = 197, DisplayName = "China - Suzhou" },
        new() { CellId = 198, DisplayName = "China - Hangzhou" },
        new() { CellId = 199, DisplayName = "China - Ningbo" },
        new() { CellId = 200, DisplayName = "China - Nanjing" },
        new() { CellId = 201, DisplayName = "China - Shenzhen" },
        new() { CellId = 202, DisplayName = "China - Dongguan" },
        new() { CellId = 203, DisplayName = "China - Tianjin" },
        new() { CellId = 204, DisplayName = "China - Chongqing" },
        new() { CellId = 205, DisplayName = "China - Shenyang" },
        new() { CellId = 206, DisplayName = "China - Dalian" },
        new() { CellId = 207, DisplayName = "US - Austin" },
        new() { CellId = 208, DisplayName = "Philippines - Cebu" },
        new() { CellId = 209, DisplayName = "Philippines - Davao" },
        new() { CellId = 210, DisplayName = "Philippines - Baguio" },
        new() { CellId = 211, DisplayName = "China - Nanning" },
        new() { CellId = 212, DisplayName = "Canary Islands" },
        new() { CellId = 213, DisplayName = "Mauritius" },
        new() { CellId = 214, DisplayName = "Reunion" },
        new() { CellId = 215, DisplayName = "Kuwait" },
    ];

    public static SteamCdnRegion Find(int cellId) =>
        All.FirstOrDefault(region => region.CellId == cellId) ?? All[0];
}
